version: '3.8'

services:
  # Frontend (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api
      - VITE_WS_URL=http://localhost:5000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend
    networks:
      - boom-karaoke

  # Backend (Node.js + Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_PATH=/app/data/database.sqlite
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    networks:
      - boom-karaoke

  # Database (SQLite - file-based, no separate container needed)
  # SQLite database file will be stored in backend/data/database.sqlite

networks:
  boom-karaoke:
    driver: bridge

volumes:
  database_data:
    driver: local

