[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  VITE_API_BASE_URL = "https://boom-karaoke-booking-schedulemongodb-uri.onrender.com/api"
  VITE_WS_URL = "https://boom-karaoke-booking-schedulemongodb-uri.onrender.com"
