#!/bin/bash

# Manual Railway Deployment Guide
echo "🚀 Railway Manual Deployment Guide"
echo "=================================="
echo ""
echo "Since Railway CLI requires interactive login, please follow these steps:"
echo ""
echo "1. 🌐 Go to https://railway.app"
echo "2. 🔐 Sign in with your GitHub account"
echo "3. 📁 Click 'New Project' → 'Deploy from GitHub repo'"
echo "4. 🔍 Select repository: samueljai120/Advanced-Calendar"
echo "5. ⚙️  Configure the service:"
echo "   - Root Directory: Boom-Booking-Isolate/backend"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "   - Health Check: /api/health"
echo ""
echo "6. 🗄️  Add PostgreSQL Database:"
echo "   - Click 'New Service' → 'Database' → 'PostgreSQL'"
echo "   - Railway will automatically provide DATABASE_URL"
echo ""
echo "7. 🔧 Set Environment Variables:"
echo "   NODE_ENV=production"
echo "   PORT=5001"
echo "   JWT_SECRET=your-super-secure-jwt-secret-for-production-change-this-now"
echo "   JWT_EXPIRES_IN=7d"
echo "   JWT_REFRESH_EXPIRES_IN=30d"
echo "   CORS_ORIGIN=https://boom-booking-frontend-5el8sm1iv-samueljai120s-projects.vercel.app"
echo "   BCRYPT_ROUNDS=12"
echo "   RATE_LIMIT_WINDOW_MS=900000"
echo "   RATE_LIMIT_MAX_REQUESTS=100"
echo "   LOG_LEVEL=info"
echo "   ENABLE_METRICS=true"
echo "   DEFAULT_TIMEZONE=America/New_York"
echo "   DEFAULT_CURRENCY=USD"
echo "   BOOKING_ADVANCE_DAYS=30"
echo "   BOOKING_MIN_DURATION=60"
echo "   BOOKING_MAX_DURATION=480"
echo ""
echo "8. 🚀 Deploy and get your Railway URL"
echo "   - Your backend will be available at: https://your-app-name.railway.app"
echo ""
echo "9. 📝 Note down your Railway URL for frontend configuration"
echo ""
echo "✅ After deployment, run the frontend configuration script:"
echo "   ./configure-frontend.sh YOUR_RAILWAY_URL"
