[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["echo 'Backend build complete'"]

[start]
cmd = "node server-railway.js"

[variables]
NODE_ENV = "production"