name: boom-booking-backend
services:
- name: api
  source_dir: backend
  github:
    repo: your-username/Advanced-Calendar
    branch: main
  run_command: node server-railway.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /api/health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: CORS_ORIGIN
    value: https://boom-booking-frontend.vercel.app

databases:
- name: boom-booking-db
  engine: PG
  version: "13"
